[2025-03-13 21:42:32,005: INFO: main: Welcome to our Custom log]
[2025-03-14 03:22:02,252: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 03:22:02,255: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 03:22:02,258: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 03:22:02,259: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 03:22:02,259: INFO: common: created directory at: artifacts]
[2025-03-14 03:22:02,281: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 03:22:02,827: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 175758
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "23237eaa68092cffd4feb41725aae8233503a84e547898e8bfc1b1589e230694"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 707E:E2DDA:17D781:1E494B:67D3D730
Accept-Ranges: bytes
Date: Fri, 14 Mar 2025 07:22:03 GMT
Via: 1.1 varnish
X-Served-By: cache-chi-klot8100095-CHI
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1741936923.072733,VS0,VE70
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: c7c98e2afcad5c77a381878b999254d08ead192c
Expires: Fri, 14 Mar 2025 07:27:03 GMT
Source-Age: 0

]
[2025-03-14 03:22:02,924: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 03:24:25,657: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 03:24:25,682: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 03:24:25,686: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 03:24:25,689: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 03:24:25,690: INFO: common: created directory at: artifacts]
[2025-03-14 03:24:25,714: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 03:24:26,144: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 175758
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "23237eaa68092cffd4feb41725aae8233503a84e547898e8bfc1b1589e230694"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 707E:E2DDA:17D781:1E494B:67D3D730
Accept-Ranges: bytes
Date: Fri, 14 Mar 2025 07:24:26 GMT
Via: 1.1 varnish
X-Served-By: cache-chi-kigq8000155-CHI
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1741937066.456648,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 9c66825b13951d95a0746fd006cffb464b1f2b21
Expires: Fri, 14 Mar 2025 07:29:26 GMT
Source-Age: 143

]
[2025-03-14 03:24:26,202: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 03:36:13,529: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 03:36:13,591: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 03:36:13,622: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 03:36:13,643: INFO: common: created directory at: artifacts]
[2025-03-14 03:36:35,553: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 03:36:35,559: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 03:36:35,566: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 03:36:35,574: INFO: common: created directory at: artifacts]
[2025-03-14 03:37:41,193: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 03:37:41,197: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 03:37:41,206: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 03:37:41,210: INFO: common: created directory at: artifacts]
[2025-03-14 03:37:41,239: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 03:45:41,547: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 03:45:41,555: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 03:45:41,559: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 03:45:41,574: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 03:45:41,600: INFO: common: created directory at: artifacts]
[2025-03-14 03:45:41,630: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 03:45:42,259: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 175758
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "23237eaa68092cffd4feb41725aae8233503a84e547898e8bfc1b1589e230694"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 707E:E2DDA:17D781:1E494B:67D3D730
Accept-Ranges: bytes
Date: Fri, 14 Mar 2025 07:45:42 GMT
Via: 1.1 varnish
X-Served-By: cache-chi-klot8100125-CHI
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1741938342.474709,VS0,VE82
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 96ece8b1fde362c40f5a057837c43971e9d42d86
Expires: Fri, 14 Mar 2025 07:50:42 GMT
Source-Age: 0

]
[2025-03-14 03:45:42,345: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 03:45:42,345: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 03:45:42,347: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 03:45:42,354: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 03:45:42,368: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 03:45:42,369: INFO: common: created directory at: artifacts]
[2025-03-14 03:45:42,405: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 03:45:42,685: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 03:50:12,968: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 03:50:12,986: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 03:50:12,997: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 03:50:13,000: INFO: common: created directory at: artifacts]
[2025-03-14 03:50:13,031: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 03:50:13,574: INFO: 741865018: Splited data into training and test sets]
[2025-03-14 03:50:13,579: INFO: 741865018: (5282, 21)]
[2025-03-14 03:50:13,581: INFO: 741865018: (1761, 21)]
[2025-03-14 03:58:40,085: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 03:58:40,094: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 03:58:40,098: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 03:58:40,102: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 03:58:40,125: INFO: common: created directory at: artifacts]
[2025-03-14 03:58:40,150: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 03:58:40,814: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 175758
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "23237eaa68092cffd4feb41725aae8233503a84e547898e8bfc1b1589e230694"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 707E:E2DDA:17D781:1E494B:67D3D730
Accept-Ranges: bytes
Date: Fri, 14 Mar 2025 07:58:41 GMT
Via: 1.1 varnish
X-Served-By: cache-chi-kigq8000029-CHI
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1741939121.951909,VS0,VE101
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: ba58115a103768b3415b4e88eb39c0e0b2e52dd7
Expires: Fri, 14 Mar 2025 08:03:41 GMT
Source-Age: 0

]
[2025-03-14 03:58:40,926: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 03:58:40,926: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 03:58:40,929: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 03:58:40,932: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 03:58:40,937: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 03:58:40,938: INFO: common: created directory at: artifacts]
[2025-03-14 03:58:40,959: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 03:58:41,158: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 03:58:41,158: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 03:58:41,164: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 03:58:41,165: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 03:58:41,167: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 03:58:41,168: INFO: common: created directory at: artifacts]
[2025-03-14 03:58:41,168: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 03:59:57,628: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 03:59:57,633: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 03:59:57,634: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 03:59:57,636: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 03:59:57,658: INFO: common: created directory at: artifacts]
[2025-03-14 03:59:57,679: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 03:59:58,060: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 175758
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "23237eaa68092cffd4feb41725aae8233503a84e547898e8bfc1b1589e230694"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 707E:E2DDA:17D781:1E494B:67D3D730
Accept-Ranges: bytes
Date: Fri, 14 Mar 2025 07:59:58 GMT
Via: 1.1 varnish
X-Served-By: cache-chi-kigq8000133-CHI
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1741939198.362651,VS0,VE1
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: d41913a52da22b45664f1fd225d39c02208af4d3
Expires: Fri, 14 Mar 2025 08:04:58 GMT
Source-Age: 77

]
[2025-03-14 03:59:58,112: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 03:59:58,112: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 03:59:58,115: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 03:59:58,116: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 03:59:58,119: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 03:59:58,120: INFO: common: created directory at: artifacts]
[2025-03-14 03:59:58,142: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 03:59:58,312: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 03:59:58,313: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 03:59:58,320: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 03:59:58,321: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 03:59:58,325: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 03:59:58,326: INFO: common: created directory at: artifacts]
[2025-03-14 03:59:58,349: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 03:59:58,634: INFO: data_transformation: Splited data into training and test sets]
[2025-03-14 03:59:58,634: INFO: data_transformation: (5282, 21)]
[2025-03-14 03:59:58,634: INFO: data_transformation: (1761, 21)]
[2025-03-14 03:59:58,636: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 04:04:35,543: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:04:35,741: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:04:35,745: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:04:35,747: INFO: common: created directory at: artifacts]
[2025-03-14 04:05:37,082: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:05:37,086: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:05:37,093: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:05:37,098: INFO: common: created directory at: artifacts]
[2025-03-14 04:05:37,131: INFO: common: created directory at: artifacts/model_trainer]
[2025-03-14 04:24:07,640: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:24:07,650: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:24:07,654: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:24:07,662: INFO: common: created directory at: artifacts]
[2025-03-14 04:24:07,666: INFO: common: created directory at: artifacts/model_trainer]
[2025-03-14 04:30:43,616: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:30:43,629: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:30:43,637: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:30:43,642: INFO: common: created directory at: artifacts]
[2025-03-14 04:30:43,646: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 04:31:06,987: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:31:06,991: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:31:06,997: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:31:07,000: INFO: common: created directory at: artifacts]
[2025-03-14 04:31:07,004: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 04:31:50,377: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:31:50,381: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:31:50,390: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:31:50,395: INFO: common: created directory at: artifacts]
[2025-03-14 04:31:50,397: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 04:31:51,846: INFO: 2872236: Saved LabelEncoder at artifacts/data_transformation\label_encoder.pkl]
[2025-03-14 04:33:41,183: INFO: 2872236: Data transformed and split into training ((5282, 13619)) and test ((1761, 13619)) sets.]
[2025-03-14 04:35:23,998: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:35:24,005: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:35:24,010: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:35:24,015: INFO: common: created directory at: artifacts]
[2025-03-14 04:35:24,017: INFO: common: created directory at: artifacts/model_trainer]
[2025-03-14 04:42:22,936: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 04:42:22,942: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:42:22,944: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:42:22,950: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:42:22,977: INFO: common: created directory at: artifacts]
[2025-03-14 04:42:23,000: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 04:42:23,478: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 175758
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "23237eaa68092cffd4feb41725aae8233503a84e547898e8bfc1b1589e230694"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 707E:E2DDA:17D781:1E494B:67D3D730
Accept-Ranges: bytes
Date: Fri, 14 Mar 2025 08:42:23 GMT
Via: 1.1 varnish
X-Served-By: cache-chi-klot8100035-CHI
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1741941744.677908,VS0,VE63
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 48da22216126a566aa875233b9f8a1aa8f50a88c
Expires: Fri, 14 Mar 2025 08:47:23 GMT
Source-Age: 0

]
[2025-03-14 04:42:23,571: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 04:42:23,571: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 04:42:23,576: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:42:23,580: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:42:23,584: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:42:23,584: INFO: common: created directory at: artifacts]
[2025-03-14 04:42:23,611: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 04:42:23,795: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 04:42:23,796: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 04:42:23,801: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:42:23,802: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:42:23,805: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:42:23,806: INFO: common: created directory at: artifacts]
[2025-03-14 04:42:23,832: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 04:42:23,833: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 04:42:23,833: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-14 04:42:23,835: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:42:23,836: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:42:23,838: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:42:23,838: INFO: common: created directory at: artifacts]
[2025-03-14 04:42:23,863: INFO: common: created directory at: artifacts/model_trainer]
[2025-03-14 04:42:23,863: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_transformation/train.csv']
Traceback (most recent call last):
  File "F:\Faseeh\New folder\4_projects\telco-customer-churn-project\main.py", line 51, in <module>
    data_ingestion.main()
  File "F:\Faseeh\New folder\4_projects\telco-customer-churn-project\src\mlProject\pipeline\stage_04_model_trainer.py", line 17, in main
    model_trainer_config.train()
  File "F:\Faseeh\New folder\4_projects\telco-customer-churn-project\src\mlProject\components\model_trainer.py", line 16, in train
    train_data = pd.read_csv(self.config.train_data_path)
  File "C:\Users\fasee\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\fasee\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\fasee\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Users\fasee\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "C:\Users\fasee\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_transformation/train.csv'
[2025-03-14 04:42:47,644: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 04:42:47,651: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:42:47,652: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:42:47,654: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:42:47,655: INFO: common: created directory at: artifacts]
[2025-03-14 04:42:47,655: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 04:42:47,655: INFO: data_ingestion: File already exists of size: ~ 172 KB]
[2025-03-14 04:42:47,690: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 04:42:47,690: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 04:42:47,692: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:42:47,693: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:42:47,695: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:42:47,696: INFO: common: created directory at: artifacts]
[2025-03-14 04:42:47,697: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 04:42:47,875: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 04:42:47,875: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 04:42:47,880: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:42:47,882: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:42:47,886: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:42:47,887: INFO: common: created directory at: artifacts]
[2025-03-14 04:42:47,888: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 04:42:47,888: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 04:42:47,888: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-14 04:42:47,891: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:42:47,892: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:42:47,895: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:42:47,896: INFO: common: created directory at: artifacts]
[2025-03-14 04:42:47,897: INFO: common: created directory at: artifacts/model_trainer]
[2025-03-14 04:42:47,898: ERROR: main: [Errno 2] No such file or directory: 'artifacts/data_transformation/train.csv']
Traceback (most recent call last):
  File "F:\Faseeh\New folder\4_projects\telco-customer-churn-project\main.py", line 51, in <module>
    data_ingestion.main()
  File "F:\Faseeh\New folder\4_projects\telco-customer-churn-project\src\mlProject\pipeline\stage_04_model_trainer.py", line 17, in main
    model_trainer_config.train()
  File "F:\Faseeh\New folder\4_projects\telco-customer-churn-project\src\mlProject\components\model_trainer.py", line 16, in train
    train_data = pd.read_csv(self.config.train_data_path)
  File "C:\Users\fasee\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parsers\readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\fasee\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parsers\readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\Users\fasee\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\Users\fasee\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\parsers\readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "C:\Users\fasee\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/data_transformation/train.csv'
[2025-03-14 04:43:26,988: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 04:43:26,994: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:43:26,997: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:43:27,001: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:43:27,002: INFO: common: created directory at: artifacts]
[2025-03-14 04:43:27,004: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 04:43:27,005: INFO: data_ingestion: File already exists of size: ~ 172 KB]
[2025-03-14 04:43:27,041: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 04:43:27,041: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 04:43:27,046: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:43:27,049: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:43:27,052: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:43:27,054: INFO: common: created directory at: artifacts]
[2025-03-14 04:43:27,055: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 04:43:27,229: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 04:43:27,229: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 04:43:27,233: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:43:27,234: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:43:27,239: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:43:27,240: INFO: common: created directory at: artifacts]
[2025-03-14 04:43:27,241: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 04:43:29,895: INFO: data_transformation: Saved LabelEncoder at artifacts/data_transformation\label_encoder.pkl]
[2025-03-14 04:45:35,080: INFO: data_transformation: Data transformed and split into training ((5282, 13619)) and test ((1761, 13619)) sets.]
[2025-03-14 04:45:35,214: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 04:45:35,215: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-14 04:45:35,223: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 04:45:35,230: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 04:45:35,238: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 04:45:35,244: INFO: common: created directory at: artifacts]
[2025-03-14 04:45:35,245: INFO: common: created directory at: artifacts/model_trainer]
[2025-03-14 04:46:10,827: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-03-14 13:43:06,648: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 13:43:06,680: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:43:06,702: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:43:06,711: INFO: common: created directory at: artifacts]
[2025-03-14 13:43:46,503: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 13:43:46,507: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:43:46,512: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:43:46,514: INFO: common: created directory at: artifacts]
[2025-03-14 13:45:11,332: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 13:45:11,338: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:45:11,344: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:45:11,349: INFO: common: created directory at: artifacts]
[2025-03-14 13:45:11,377: INFO: common: created directory at: artifacts/model_evaluation]
[2025-03-14 13:45:29,413: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json]
[2025-03-14 13:52:59,105: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 13:52:59,121: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:52:59,144: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:52:59,151: INFO: common: created directory at: artifacts]
[2025-03-14 13:52:59,154: INFO: common: created directory at: artifacts/model_evaluation]
[2025-03-14 13:55:23,050: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 13:55:23,060: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:55:23,073: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:55:23,079: INFO: common: created directory at: artifacts]
[2025-03-14 13:55:23,089: INFO: common: created directory at: artifacts/model_evaluation]
[2025-03-14 13:56:37,583: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 13:56:37,590: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:56:37,596: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:56:37,598: INFO: common: created directory at: artifacts]
[2025-03-14 13:56:37,600: INFO: common: created directory at: artifacts/model_evaluation]
[2025-03-14 13:57:02,015: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 13:57:02,019: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 13:57:02,024: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 13:57:02,029: INFO: common: created directory at: artifacts]
[2025-03-14 13:57:02,032: INFO: common: created directory at: artifacts/model_evaluation]
[2025-03-14 14:03:03,375: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 14:03:03,386: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 14:03:03,396: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 14:03:03,400: INFO: common: created directory at: artifacts]
[2025-03-14 14:03:03,403: INFO: common: created directory at: artifacts/model_evaluation]
[2025-03-14 14:03:23,941: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 14:03:23,945: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 14:03:23,952: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 14:03:23,954: INFO: common: created directory at: artifacts]
[2025-03-14 14:03:23,956: INFO: common: created directory at: artifacts/model_evaluation]
[2025-03-14 14:03:30,498: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json]
[2025-03-14 14:40:27,535: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-03-14 14:40:27,553: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 14:40:27,562: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 14:40:27,571: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 14:40:27,600: INFO: common: created directory at: artifacts]
[2025-03-14 14:40:27,629: INFO: common: created directory at: artifacts/data_ingestion]
[2025-03-14 14:40:28,542: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 175758
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "23237eaa68092cffd4feb41725aae8233503a84e547898e8bfc1b1589e230694"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 8D3B:1BEB56:2BC354:35698D:67D4781B
Accept-Ranges: bytes
Date: Fri, 14 Mar 2025 18:40:28 GMT
Via: 1.1 varnish
X-Served-By: cache-chi-kigq8000097-CHI
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1741977628.068988,VS0,VE355
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: ba607295b5bfa0651c07f45ebbc86ef969d70b3d
Expires: Fri, 14 Mar 2025 18:45:28 GMT
Source-Age: 0

]
[2025-03-14 14:40:28,635: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-03-14 14:40:28,638: INFO: main: >>>>>> stage Data Validation stage started <<<<<<]
[2025-03-14 14:40:28,657: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 14:40:28,665: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 14:40:28,673: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 14:40:28,674: INFO: common: created directory at: artifacts]
[2025-03-14 14:40:28,708: INFO: common: created directory at: artifacts/data_validation]
[2025-03-14 14:40:29,084: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x]
[2025-03-14 14:40:29,085: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<]
[2025-03-14 14:40:29,138: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 14:40:29,159: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 14:40:29,164: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 14:40:29,166: INFO: common: created directory at: artifacts]
[2025-03-14 14:40:29,205: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 14:40:32,648: INFO: data_transformation: Saved LabelEncoder at artifacts/data_transformation\label_encoder.pkl]
[2025-03-14 14:42:45,357: INFO: data_transformation: Data transformed and split into training ((5282, 13619)) and test ((1761, 13619)) sets.]
[2025-03-14 14:42:45,578: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x]
[2025-03-14 14:42:45,578: INFO: main: >>>>>> stage Model Trainer stage started <<<<<<]
[2025-03-14 14:42:45,587: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 14:42:45,591: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 14:42:45,605: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 14:42:45,607: INFO: common: created directory at: artifacts]
[2025-03-14 14:42:45,637: INFO: common: created directory at: artifacts/model_trainer]
[2025-03-14 14:43:17,102: INFO: main: >>>>>> stage Model Trainer stage completed <<<<<<

x==========x]
[2025-03-14 14:43:17,103: INFO: main: >>>>>> stage Model evaluation stage started <<<<<<]
[2025-03-14 14:43:17,110: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 14:43:17,117: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 14:43:17,129: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 14:43:17,130: INFO: common: created directory at: artifacts]
[2025-03-14 14:43:17,153: INFO: common: created directory at: artifacts/model_evaluation]
[2025-03-14 14:43:25,642: INFO: common: json file saved at: artifacts\model_evaluation\metrics.json]
[2025-03-14 14:43:47,076: INFO: main: >>>>>> stage Model evaluation stage completed <<<<<<

x==========x]
[2025-03-14 14:53:25,157: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.2.1.40:8080]
[2025-03-14 14:53:25,162: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-14 14:53:25,192: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 14:53:27,824: WARNING: _internal:  * Debugger is active!]
[2025-03-14 14:53:27,845: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 14:53:31,362: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 14:53:31] "GET / HTTP/1.1" 200 -]
[2025-03-14 14:53:31,710: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 14:53:31] "[33mGET /static/assets/img/background.jpg HTTP/1.1[0m" 404 -]
[2025-03-14 14:53:31,843: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 14:53:31] "GET /static/css/styles.css HTTP/1.1" 200 -]
[2025-03-14 14:53:32,169: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 14:53:32] "GET / HTTP/1.1" 200 -]
[2025-03-14 14:53:33,090: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 14:53:33] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-03-14 14:58:12,798: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 14:58:12] "POST /predict HTTP/1.1" 200 -]
[2025-03-14 14:58:13,190: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 14:58:13] "GET /predict HTTP/1.1" 200 -]
[2025-03-14 14:58:46,679: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\joblib\\numpy_pickle.py', reloading]
[2025-03-14 14:58:46,748: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\joblib\\numpy_pickle_compat.py', reloading]
[2025-03-14 14:58:46,758: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\joblib\\numpy_pickle_utils.py', reloading]
[2025-03-14 14:58:46,798: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\joblib\\compressor.py', reloading]
[2025-03-14 14:58:47,215: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\numpy\\_typing\\_dtype_like.py', reloading]
[2025-03-14 14:58:48,027: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 14:58:52,747: WARNING: _internal:  * Debugger is active!]
[2025-03-14 14:58:52,756: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 14:59:00,494: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 14:59:00,497: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 14:59:00,497: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 14:59:01,185: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 14:59:04,322: WARNING: _internal:  * Debugger is active!]
[2025-03-14 14:59:04,337: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 14:59:06,011: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 14:59:06] "POST /predict HTTP/1.1" 200 -]
[2025-03-14 14:59:06,202: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 14:59:06] "GET /predict HTTP/1.1" 200 -]
[2025-03-14 14:59:20,489: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 14:59:20] "POST /predict HTTP/1.1" 200 -]
[2025-03-14 14:59:20,619: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 14:59:20] "GET /predict HTTP/1.1" 200 -]
[2025-03-14 15:01:10,574: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\jinja2\\loaders.py', reloading]
[2025-03-14 15:01:10,623: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\flask\\cli.py', reloading]
[2025-03-14 15:01:10,680: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\click\\__init__.py', reloading]
[2025-03-14 15:01:10,720: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\click\\core.py', reloading]
[2025-03-14 15:01:10,816: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\click\\decorators.py', reloading]
[2025-03-14 15:01:10,855: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\flask\\helpers.py', reloading]
[2025-03-14 15:01:11,431: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 15:01:12,914: WARNING: _internal:  * Debugger is active!]
[2025-03-14 15:01:12,923: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 15:01:16,719: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:01:16] "GET / HTTP/1.1" 200 -]
[2025-03-14 15:01:18,814: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:01:18] "POST /predict HTTP/1.1" 200 -]
[2025-03-14 15:01:18,949: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:01:18] "GET /predict HTTP/1.1" 200 -]
[2025-03-14 15:01:22,690: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:01:22] "GET / HTTP/1.1" 200 -]
[2025-03-14 15:01:22,789: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:01:22] "GET / HTTP/1.1" 200 -]
[2025-03-14 15:01:22,800: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:01:22] "[33mGET /static/assets/img/background.jpg HTTP/1.1[0m" 404 -]
[2025-03-14 15:01:22,870: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:01:22] "[36mGET /static/css/styles.css HTTP/1.1[0m" 304 -]
[2025-03-14 15:01:39,089: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:01:39] "POST /predict HTTP/1.1" 200 -]
[2025-03-14 15:01:39,252: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:01:39] "GET /predict HTTP/1.1" 200 -]
[2025-03-14 15:03:11,526: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 15:03:11,529: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 15:03:11,531: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 15:03:12,716: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 15:03:14,920: WARNING: _internal:  * Debugger is active!]
[2025-03-14 15:03:14,935: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 15:03:15,043: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:03:15] "GET / HTTP/1.1" 200 -]
[2025-03-14 15:03:18,924: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\sklearn\\utils\\validation.py', reloading]
[2025-03-14 15:03:18,927: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:03:18] "POST /predict HTTP/1.1" 200 -]
[2025-03-14 15:03:19,033: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:03:19] "GET /predict HTTP/1.1" 200 -]
[2025-03-14 15:03:19,613: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 15:03:21,120: WARNING: _internal:  * Debugger is active!]
[2025-03-14 15:03:21,128: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 15:04:04,403: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\os.py', reloading]
[2025-03-14 15:04:04,983: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 15:04:06,517: WARNING: _internal:  * Debugger is active!]
[2025-03-14 15:04:06,525: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 15:04:06,773: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\sklearn\\model_selection\\_split.py', reloading]
[2025-03-14 15:04:06,952: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\joblib\\logger.py', reloading]
[2025-03-14 15:04:07,005: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\numpy\\_typing\\_nbit.py', reloading]
[2025-03-14 15:04:07,076: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\sklearn\\utils\\__init__.py', reloading]
[2025-03-14 15:04:07,101: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\sklearn\\utils\\_indexing.py', reloading]
[2025-03-14 15:04:07,114: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\scipy\\special\\__init__.py', reloading]
[2025-03-14 15:04:07,191: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\scipy\\special\\_basic.py', reloading]
[2025-03-14 15:04:07,253: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\sklearn\\utils\\metadata_routing.py', reloading]
[2025-03-14 15:04:07,256: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\sklearn\\utils\\_array_api.py', reloading]
[2025-03-14 15:04:07,280: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\sklearn\\utils\\_param_validation.py', reloading]
[2025-03-14 15:04:07,290: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\scipy\\special\\_multiufuncs.py', reloading]
[2025-03-14 15:04:07,319: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\sklearn\\utils\\extmath.py', reloading]
[2025-03-14 15:04:07,337: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\sklearn\\utils\\_metadata_requests.py', reloading]
[2025-03-14 15:04:07,387: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\sklearn\\utils\\multiclass.py', reloading]
[2025-03-14 15:04:08,013: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 15:04:10,035: WARNING: _internal:  * Debugger is active!]
[2025-03-14 15:04:10,042: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 15:06:10,526: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\sklearn\\preprocessing\\_encoders.py', reloading]
[2025-03-14 15:06:10,558: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\sklearn\\base.py', reloading]
[2025-03-14 15:06:11,597: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 15:06:14,026: WARNING: _internal:  * Debugger is active!]
[2025-03-14 15:06:14,035: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 15:06:22,574: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 15:06:22,587: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:06:22,593: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:06:22,600: INFO: common: created directory at: artifacts]
[2025-03-14 15:06:22,604: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 15:06:25,890: INFO: 2359711712: Saved preprocessor at artifacts/data_transformation\preprocessor.pkl]
[2025-03-14 15:06:25,959: INFO: 2359711712: Saved LabelEncoder at artifacts/data_transformation\label_encoder.pkl]
[2025-03-14 15:06:56,501: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 15:06:56,508: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 15:06:57,075: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 15:08:30,021: INFO: 2359711712: Data transformed and split into training ((5282, 13619)) and test ((1761, 13619)) sets.]
[2025-03-14 15:10:21,729: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.2.1.40:8080]
[2025-03-14 15:10:21,731: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-14 15:10:21,756: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 15:10:23,276: WARNING: _internal:  * Debugger is active!]
[2025-03-14 15:10:23,342: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 15:10:28,478: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:10:28] "POST /predict HTTP/1.1" 200 -]
[2025-03-14 15:10:28,654: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:10:28] "[31m[1mGET /predict HTTP/1.1[0m" 405 -]
[2025-03-14 15:10:56,686: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 15:10:56,692: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 15:10:57,236: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 15:10:59,354: WARNING: _internal:  * Debugger is active!]
[2025-03-14 15:10:59,368: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 15:11:01,178: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:11:01] "GET / HTTP/1.1" 200 -]
[2025-03-14 15:11:04,122: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:11:04] "POST /predict HTTP/1.1" 200 -]
[2025-03-14 15:11:04,255: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:11:04] "[31m[1mGET /predict HTTP/1.1[0m" 405 -]
[2025-03-14 15:12:31,087: INFO: _internal:  * Detected change in 'C:\\Users\\fasee\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\sklearn\\preprocessing\\_label.py', reloading]
[2025-03-14 15:12:31,770: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 15:12:33,003: WARNING: _internal:  * Debugger is active!]
[2025-03-14 15:12:33,016: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 15:14:49,735: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 15:14:49,746: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:14:49,756: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:14:49,762: INFO: common: created directory at: artifacts]
[2025-03-14 15:14:49,766: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 15:14:53,461: INFO: 812645982: Saved preprocessor at artifacts/data_transformation\preprocessor.pkl]
[2025-03-14 15:14:53,548: INFO: 812645982: Saved LabelEncoder at artifacts/data_transformation\label_encoder.pkl]
[2025-03-14 15:15:18,387: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\src\\mlProject\\pipeline\\prediction.py', reloading]
[2025-03-14 15:15:18,397: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\src\\mlProject\\pipeline\\prediction.py', reloading]
[2025-03-14 15:15:19,468: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 15:15:21,793: WARNING: _internal:  * Debugger is active!]
[2025-03-14 15:15:21,810: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 15:17:18,668: INFO: 812645982: Data transformed and split into training ((5282, 13619)) and test ((1761, 13619)) sets.]
[2025-03-14 15:17:29,547: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:17:29] "GET / HTTP/1.1" 200 -]
[2025-03-14 15:17:37,745: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:17:37] "POST /predict HTTP/1.1" 200 -]
[2025-03-14 15:17:38,093: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:17:38] "[31m[1mGET /predict HTTP/1.1[0m" 405 -]
[2025-03-14 15:17:49,467: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\src\\mlProject\\pipeline\\prediction.py', reloading]
[2025-03-14 15:17:49,473: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\src\\mlProject\\pipeline\\prediction.py', reloading]
[2025-03-14 15:17:49,481: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\src\\mlProject\\pipeline\\prediction.py', reloading]
[2025-03-14 15:17:50,407: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 15:17:53,637: WARNING: _internal:  * Debugger is active!]
[2025-03-14 15:17:53,649: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 15:17:56,661: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:17:56] "POST /predict HTTP/1.1" 200 -]
[2025-03-14 15:17:56,818: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:17:56] "[31m[1mGET /predict HTTP/1.1[0m" 405 -]
[2025-03-14 15:33:20,757: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-03-14 15:33:20,770: INFO: common: yaml file: params.yaml loaded successfully]
[2025-03-14 15:33:20,778: INFO: common: yaml file: schema.yaml loaded successfully]
[2025-03-14 15:33:20,786: INFO: common: created directory at: artifacts]
[2025-03-14 15:33:20,790: INFO: common: created directory at: artifacts/data_transformation]
[2025-03-14 15:33:24,215: INFO: 2081816972: Saved preprocessor at artifacts/data_transformation\preprocessor.pkl]
[2025-03-14 15:33:24,267: INFO: 2081816972: Saved LabelEncoder at artifacts/data_transformation\label_encoder.pkl]
[2025-03-14 15:33:58,106: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\src\\mlProject\\pipeline\\prediction.py', reloading]
[2025-03-14 15:33:58,193: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\src\\mlProject\\pipeline\\prediction.py', reloading]
[2025-03-14 15:33:59,946: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 15:34:02,604: WARNING: _internal:  * Debugger is active!]
[2025-03-14 15:34:02,661: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 15:34:10,711: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 15:34:10,717: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 15:34:10,721: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 15:34:11,068: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 15:34:13,335: WARNING: _internal:  * Debugger is active!]
[2025-03-14 15:34:13,346: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 15:34:21,100: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:34:21] "GET / HTTP/1.1" 200 -]
[2025-03-14 15:34:21,498: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:34:21] "[33mGET /static/assets/img/background.jpg HTTP/1.1[0m" 404 -]
[2025-03-14 15:34:21,545: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:34:21] "[36mGET /static/css/styles.css HTTP/1.1[0m" 304 -]
[2025-03-14 15:34:22,907: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:34:22] "GET / HTTP/1.1" 200 -]
[2025-03-14 15:34:37,334: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:34:37] "POST /predict HTTP/1.1" 200 -]
[2025-03-14 15:34:37,463: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:34:37] "[31m[1mGET /predict HTTP/1.1[0m" 405 -]
[2025-03-14 15:34:56,678: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 15:34:56,682: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 15:34:56,683: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 15:34:57,519: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 15:34:59,316: WARNING: _internal:  * Debugger is active!]
[2025-03-14 15:34:59,323: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 15:35:00,165: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:00] "GET / HTTP/1.1" 200 -]
[2025-03-14 15:35:03,297: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:03] "GET / HTTP/1.1" 200 -]
[2025-03-14 15:35:03,451: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:03] "GET / HTTP/1.1" 200 -]
[2025-03-14 15:35:03,458: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:03] "[33mGET /static/assets/img/background.jpg HTTP/1.1[0m" 404 -]
[2025-03-14 15:35:03,534: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:03] "[36mGET /static/css/styles.css HTTP/1.1[0m" 304 -]
[2025-03-14 15:35:11,841: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:11] "GET / HTTP/1.1" 200 -]
[2025-03-14 15:35:11,956: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:11] "[36mGET /static/css/styles.css HTTP/1.1[0m" 304 -]
[2025-03-14 15:35:11,972: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:11] "[33mGET /static/assets/img/background.jpg HTTP/1.1[0m" 404 -]
[2025-03-14 15:35:11,978: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:11] "GET / HTTP/1.1" 200 -]
[2025-03-14 15:35:15,635: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 15:35:15,640: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 15:35:15,641: INFO: _internal:  * Detected change in 'F:\\Faseeh\\New folder\\4_projects\\telco-customer-churn-project\\app.py', reloading]
[2025-03-14 15:35:16,718: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 15:35:18,209: WARNING: _internal:  * Debugger is active!]
[2025-03-14 15:35:18,218: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 15:35:19,144: INFO: 2081816972: Data transformed and split into training ((5282, 13619)) and test ((1761, 13619)) sets.]
[2025-03-14 15:35:43,269: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:43] "POST /predict HTTP/1.1" 200 -]
[2025-03-14 15:35:43,537: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:43] "[36mGET /static/css/styles.css HTTP/1.1[0m" 304 -]
[2025-03-14 15:35:43,718: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:43] "GET /static/js/scripts.js HTTP/1.1" 200 -]
[2025-03-14 15:35:43,912: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:43] "[33mGET /static/assets/img/wine.gif HTTP/1.1[0m" 404 -]
[2025-03-14 15:35:43,951: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:43] "[31m[1mGET /predict HTTP/1.1[0m" 405 -]
[2025-03-14 15:35:44,840: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:44] "GET /static/assets/favicon.ico HTTP/1.1" 200 -]
[2025-03-14 15:35:59,795: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:59] "POST /predict HTTP/1.1" 200 -]
[2025-03-14 15:35:59,887: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:59] "[36mGET /static/css/styles.css HTTP/1.1[0m" 304 -]
[2025-03-14 15:35:59,895: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:59] "[36mGET /static/js/scripts.js HTTP/1.1[0m" 304 -]
[2025-03-14 15:35:59,996: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:59] "[33mGET /static/assets/img/wine.gif HTTP/1.1[0m" 404 -]
[2025-03-14 15:35:59,998: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:35:59] "[31m[1mGET /predict HTTP/1.1[0m" 405 -]
[2025-03-14 15:36:00,556: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:36:00] "[36mGET /static/assets/favicon.ico HTTP/1.1[0m" 304 -]
[2025-03-14 15:36:07,899: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:36:07] "[31m[1mGET /predict HTTP/1.1[0m" 405 -]
[2025-03-14 15:39:09,859: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.2.1.40:8080]
[2025-03-14 15:39:09,861: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-03-14 15:39:09,888: INFO: _internal:  * Restarting with watchdog (windowsapi)]
[2025-03-14 15:39:11,473: WARNING: _internal:  * Debugger is active!]
[2025-03-14 15:39:11,482: INFO: _internal:  * Debugger PIN: 884-394-630]
[2025-03-14 15:39:17,870: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:39:17] "POST /predict HTTP/1.1" 200 -]
[2025-03-14 15:39:18,145: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:39:18] "[36mGET /static/js/scripts.js HTTP/1.1[0m" 304 -]
[2025-03-14 15:39:18,159: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:39:18] "[36mGET /static/css/styles.css HTTP/1.1[0m" 304 -]
[2025-03-14 15:39:18,220: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:39:18] "[33mGET /static/assets/img/wine.gif HTTP/1.1[0m" 404 -]
[2025-03-14 15:39:18,284: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:39:18] "[31m[1mGET /predict HTTP/1.1[0m" 405 -]
[2025-03-14 15:39:18,580: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:39:18] "[36mGET /static/assets/favicon.ico HTTP/1.1[0m" 304 -]
[2025-03-14 15:39:21,735: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:39:21] "GET / HTTP/1.1" 200 -]
[2025-03-14 15:39:21,847: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:39:21] "[36mGET /static/css/styles.css HTTP/1.1[0m" 304 -]
[2025-03-14 15:39:21,848: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:39:21] "GET / HTTP/1.1" 200 -]
[2025-03-14 15:39:21,861: INFO: _internal: 127.0.0.1 - - [14/Mar/2025 15:39:21] "[33mGET /static/assets/img/background.jpg HTTP/1.1[0m" 404 -]
